# Generated by Django 5.2.4 on 2025-08-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Std_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
