# Generated by Django 5.2.4 on 2025-08-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Std_records', '0002_rename_students_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
