# Generated by Django 5.2.4 on 2025-09-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Std_records', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='std_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='std_city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='std_mail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='std_name',
        ),
    ]
