# Generated by Django 5.2.4 on 2025-09-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Std_records', '0007_rename_age_student_std_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
