# Generated by Django 5.2.4 on 2025-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Std_records', '0008_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_age', models.IntegerField()),
                ('std_city', models.CharField(max_length=50)),
                ('std_mail', models.EmailField(max_length=60)),
            ],
        ),
    ]
